### ISSUE TITLE
Identify classes

### ISSUE THREAD

**Issue by symphonyalpha** [afiqdanialll/INF2001-P8-4#51]
Task Details: Identify and define the classes that represent system objects/entities.

Task Goals: To establish a clear understanding of the key classes within the system.

Success/Completion Criteria: A list of identified classes with concise descriptions.

Allocated Time: 1/10/23 to 3/10/23

Start Date: 1/10/23

End Date: 3/10/23

Task Owner: Afiq

Task status: Backlog 

Task Priority:

**Comment by afiqdanialll** [comment]
Task Comments: To be updated whenever there is a major milestone for the issue.

Describe the work done in detail. 
**This work involves the possible classes that can be created for the class diagram based on the use case descriptions and diagrams**

Has this work been committed to the repo?
**yes**

How does the work affect the completion deadline.
**This is required in order to fulfill the m2 submission requirements and aid in the development of the sequence and component diagram.**

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
**no**

Start and end date of the work done for this comment.
**1 Oct 2023 - 3 Oct 2023**
